name: Testing to Prod Deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy-to-kubernetes:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Pull Docker Images from DockerHub
      - name: Pull Backend Docker Image
        run: |
          docker pull yourusername/backend:testing
          docker tag yourusername/backend:testing yourusername/backend:prod
          docker push yourusername/backend:prod

      - name: Pull Frontend Docker Image
        run: |
          docker pull yourusername/frontend:testing
          docker tag yourusername/frontend:prod
          docker push yourusername/frontend:prod

      # Install Minikube and Set Up Kubernetes
      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          sudo apt-get install -y conntrack

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      # Apply Kubernetes Manifests
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
