name: CD Pipeline - Testing Deployment

on:
  push:
    branches:
      - testing

jobs:
  deploy-to-testing:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Pull the latest Docker images
    - name: Pull Backend Docker Image
      run: |
        docker pull bilalkhan980/mbackend:latest

    - name: Pull Frontend Docker Image
      run: |
        docker pull bilalkhan980/mfrontend:latest

    # Set up Minikube
    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube start

    # Display Minikube IP
    - name: Display Minikube IP
      run: |
        minikube ip    

    # Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    # Load Docker images into Minikube
    - name: Load Docker Images into Minikube
      run: |
        minikube image load bilalkhan980/mbackend:latest
        minikube image load bilalkhan980/mfrontend:latest

    # Deploy the application to Minikube
    - name: Deploy Application to Testing Environment
      run: |
       kubectl apply -f ./k8s/frontend_deployment.yaml
       kubectl apply -f ./k8s/frontend_service.yaml
       kubectl apply -f ./k8s/backend_deployment.yaml
       kubectl apply -f ./k8s/backend_service.yaml

    # Verify the deployment
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services
