name: CI Pipeline

on:
  push:
    branches:
      - testing

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Setup Python for Backend
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Install dependencies and run tests
      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Backend Tests
        run: |
          cd backend
          pytest tests

      # Build Docker Images
      - name: Build Backend Docker Image
        run: |
          docker build -t yourusername/backend:testing ./backend

      - name: Build Frontend Docker Image
        run: |
          docker build -t yourusername/frontend:testing ./my-app

      # Push Docker Images to DockerHub
      - name: Push Docker Images to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push yourusername/backend:testing
          docker push yourusername/frontend:testing
