name: CI Pipeline - Dev to Testing

on:
  push:
    branches:
      - dev

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        cd Backend
        pip install pytest

    - name: Run Unit Tests (Optional)
       
      run: |
        cd Backend 
        pytest tests/test_main.py


    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Push Backend Docker image
    - name: Build and Push Backend Docker Image
      run: |
        docker build -t bilalkhan980/mbackend:latest -f Backend/Dockerfile Backend/
        docker push bilalkhan980/mbackend:latest

    # Build and Push Frontend Docker image
    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t bilalkhan980/mfrontend:latest -f my-app/Dockerfile my-app/
        docker push bilalkhan980/mfrontend:latest